name: CI - PR checks (lint/build/test)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: []

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run type-check

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - name: Build (safe)
        env:
          SKIP_ENV_VALIDATION: true
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage --passWithNoTests
        env:
          CI: true
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage
          path: ./coverage || ./coverage/lcov.info
